/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor */

#ifndef _Included_org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor
#define _Included_org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor
 * Method:    initializeJavaApiCallIds
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor_initializeJavaApiCallIds
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor
 * Method:    startOOMMonitoringNative
 * Signature: (Ljava/util/concurrent/ConcurrentMap;Ljava/util/concurrent/ConcurrentLinkedQueue;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor_startOOMMonitoringNative
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor
 * Method:    registerCgroupNative
 * Signature: (Ljava/util/concurrent/ConcurrentLinkedQueue;Ljava/util/concurrent/ConcurrentLinkedQueue;Ljava/util/concurrent/ConcurrentMap;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_storm_container_cgroup_monitor_CgroupOOMMonitor_registerCgroupNative
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
